Feature/homework1
designatedContributor/Fortune-Teller pull request #3
Opened 2019-09-23 08:11 UTC by designatedContributor

2019-09-23 12:59 UTC, yalantis-ios-school commented on .swiftlint.yml
> +line_length:
мы не выключаем стандартные правила и не меняем значения констант. Можно поиграться, попробовать изменения, но в прод уходит стандартный файл. Можно только добавить правил, если хочется

2019-09-23 12:59 UTC, yalantis-ios-school commented on FortuneTeller.xcodeproj/project.pbxproj
> +		0498632378BDADAB01271077 /* libPods-FortuneTeller.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 40B2BF791BB6A65821C21E5E /* libPods-FortuneTeller.a */; };
общие замечания.
Папка Pods запушена в репозитории.
Смерженные ветки надо удалять из репозитория

2019-09-23 12:59 UTC, yalantis-ios-school commented on FortuneTeller/Controllers/MainViewController.swift
> +        if isFlipped == false && motion == .motionShake {
теперь контент методов motionEnded и motionCancelled задублированный

2019-09-23 12:59 UTC, yalantis-ios-school commented on FortuneTeller/Controllers/SettingsViewController.swift
> +        let alertController = UIAlertController(title: "You saved answer", message: message, preferredStyle: .alert)
строки также следует добавить в автогенерацию SwiftGen

2019-09-23 12:59 UTC, yalantis-ios-school commented on FortuneTeller/Controllers/SettingsViewController.swift
> +    let typeArray: [AnswerType] = [.Affirmative, .Neutral, .Contrary]
просто `types` достаточно

2019-09-23 12:59 UTC, yalantis-ios-school commented on FortuneTeller/Global/AppDelegate.swift
>          return true
надо удалить пустые методы из AppDelegate

2019-09-23 12:59 UTC, yalantis-ios-school commented on FortuneTeller/View/Model/View/Model/ActivityModel.swift
> +        networkService?.getDataFromServer { networkAnswer in
тут следовало бы сделать акцент не на то, откуда данные берутся, а на то, какие это данные. `getAnswer`, например. `networkAnswer` соответственно тоже не нужен, просто `answer`

2019-09-23 12:59 UTC, yalantis-ios-school commented on FortuneTeller/View/Model/View/Model/UserDefaultAnswer.swift
>      func saveUserAnswer(answer: String, type: AnswerType) {
func save(answer: String, type: AnswerType)

2019-09-23 12:59 UTC, yalantis-ios-school commented on Podfile
> + pod 'SwiftLint'
хорошим тоном является указание минимальной версии пода

2019-09-23 12:59 UTC, yalantis-ios-school commented on FortuneTeller/Swiftgen/Colors.swift
> +// swiftlint:disable all
не увидел генерации swiftgen для картинок

2019-09-25 11:59 UTC, designatedContributor commented on FortuneTeller.xcodeproj/project.pbxproj
> +		0498632378BDADAB01271077 /* libPods-FortuneTeller.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 40B2BF791BB6A65821C21E5E /* libPods-FortuneTeller.a */; };
+

2019-09-25 12:01 UTC, designatedContributor commented on FortuneTeller/Controllers/MainViewController.swift
> +        if isFlipped == false && motion == .motionShake {
пока вернулся к motionBegan
думаю над идеей с двумя таймерами

2019-09-25 12:01 UTC, designatedContributor commented on FortuneTeller/Controllers/SettingsViewController.swift
> +        let alertController = UIAlertController(title: "You saved answer", message: message, preferredStyle: .alert)
добавил

2019-09-25 12:02 UTC, designatedContributor commented on FortuneTeller/Controllers/SettingsViewController.swift
> +    let typeArray: [AnswerType] = [.Affirmative, .Neutral, .Contrary]
'keep it short and simple'
есть.

2019-09-25 12:04 UTC, designatedContributor commented on Podfile
> + pod 'SwiftLint'
спасибо, исправил

2019-09-25 12:04 UTC, designatedContributor commented on FortuneTeller/Swiftgen/Colors.swift
> +// swiftlint:disable all
добавил

2019-09-25 12:43 UTC, yalantis-ios-school requested changes

2019-09-25 12:43 UTC, yalantis-ios-school commented on FortuneTeller/Swiftgen/assets-images.swift
> +  internal static let _8BallInsideACircle2 = ImageAsset(name: "8-ball-inside-a-circle-2")
генерация есть, а где использование? надо из кода сеттить картинки теперь

2019-09-25 13:02 UTC, designatedContributor commented on FortuneTeller/Swiftgen/assets-images.swift
> +  internal static let _8BallInsideACircle2 = ImageAsset(name: "8-ball-inside-a-circle-2")
картинки задействовал

2019-09-25 13:57 UTC, yalantis-ios-school approved these changes

2019-09-25 13:57 UTC, merged