mvvm with active model
designatedContributor/Fortune-Teller pull request #4
Opened 2019-10-01 14:29 UTC by designatedContributor

2019-10-01 17:36 UTC, yalantis-ios-school requested changes

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Presentation/ViewControllers/TabBarViewController.swift
> +        let activityModel = ActiveModel(networkService: NetwotkingService(), userDefaultAnswer: UserDefaultAnswer())
в проекте есть 5 ворнингов от SwiftLint. Их быть не должно

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Presentation/View Models/MainViewModel.swift
> +    private let activityModel: ActiveModel
в этом файле выравнивание поплыло

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Presentation/View Models/MainViewModel.swift
> +    var response: ((String, AnswerType) -> Void)? {
установка этой кложуры инициирует запрос в сеть. Это вообще не очевидно. 
+ то, как выглядит код в контроллере
`mainViewModel?.response = { [weak self] (answer, type) in
                self?.setAnswer(answer: answer, type: type)
                self?.flip()
            }`
выглядит так, будто избыточно на каждый шейк сеттится одна и та же кложура. 
В общем, это надо переписать на обычный метод с комплишн кложурой, и в модели тоже

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Application/ActiveModel.swift
> +class ActiveModel {
`AnswersModel` лучше описывает назначение этой модели

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Presentation/View Models/MainViewModel.swift
> +init(activityModel: ActiveModel) {
не увидел Presentable сущности (просто String не считается). Не увидел Data сущности. Есть Response, который представляет Application слой и всё. Сейчас, возможно, внедрение этих трех слоев данных выглядит избыточным, но такое требование к этому ДЗ

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Application/Services/UserDefaultAnswer.swift
> +    func getRandomAnswer() -> Response {
этот объект представляет собой сервис слоя Data. Он должен работать с Data сущностью

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Application/ActiveModel.swift
>      let networkService: NetwotkingService?
не увидел протоколов для сервисов. Это требование прописано в задании

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Presentation/View Models/SettingsViewModel.swift
> +    let types: [AnswerType] = [.affirmative, .neutral, .contrary]
зачем дублировать данные из AnswerType? Тут можно ограничиться использованием AnswerType.allCases (уже не будем заморачиваться со слоями)

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Presentation/View Models/SettingsViewModel.swift
> +protocol SettingsViewModelProtocol: class {
лучше `SettingsViewModelDelegate`

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Presentation/ViewControllers/MainViewController.swift
> +        mainViewModel.isFlipped = !mainViewModel.isFlipped
это свойство можно не хранить в view model. Если бы это было частью состояния модели, тогда через вью модель из модели подтягивался бы стейт. А так можно хранить флаг в контроллере.

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Presentation/View Models/SettingsViewModel.swift
> +        guard let isSaved = isAnswerSaved else { return }
внутри модели isSaved не должен возвращать optional. Должен быть просто Bool. Если в userDefaultAnswer не нашлось такого ответа, значит он не сохранен.

2019-10-01 17:36 UTC, yalantis-ios-school commented on FortuneTeller/Presentation/ViewControllers/SettingsViewController.swift
> +        typeTextField.text = settingsViewModel.types[0].toString()
`toString()` является частью форматирования данных, и должен быть в вью модели. Контроллер только заполняет данными UI

2019-10-02 11:41 UTC, designatedContributor commented on FortuneTeller/Presentation/ViewControllers/TabBarViewController.swift
> +        let activityModel = ActiveModel(networkService: NetwotkingService(), userDefaultAnswer: UserDefaultAnswer())
остался один ворнинг от метода из коробки :shouldReturnCharactersIn

2019-10-02 11:45 UTC, designatedContributor commented on FortuneTeller/Presentation/View Models/MainViewModel.swift
> +    var response: ((String, AnswerType) -> Void)? {
Согласен, выглядило стремно, зато теперь кложуры ясны. Изменил.

2019-10-02 11:49 UTC, designatedContributor commented on FortuneTeller/Presentation/View Models/MainViewModel.swift
> +init(activityModel: ActiveModel) {
Добавил, надо было хорошо презентацию посмотреть, my bad

2019-10-02 11:50 UTC, designatedContributor commented on FortuneTeller/Presentation/View Models/SettingsViewModel.swift
> +    let types: [AnswerType] = [.affirmative, .neutral, .contrary]
про этот трюк с Enum не знал, спасибо большое

2019-10-03 07:57 UTC, yalantis-ios-school requested changes
Исправьте замечания и самостоятельно закройте МР

2019-10-03 07:57 UTC, yalantis-ios-school commented on FortuneTeller/Application/ActiveModel/AnswersModel.swift
> +    let networkService: NetworkingServiceDelegate
private

2019-10-03 07:57 UTC, yalantis-ios-school commented on FortuneTeller/Application/ActiveModel/AnswersModel.swift
> +    let userDefaultAnswer: UserDefaultAnswerDelegate
private

2019-10-03 07:57 UTC, yalantis-ios-school commented on FortuneTeller/Global/Protocols.swift
> +protocol UserDefaultAnswerDelegate: class {
нейминг Delegate подразумевает паттерн Делегат, когда объект какую-то логику делегирует другому. В данном случае ничего не делегируется. То же самое с NetworkingServiceDelegate

2019-10-03 07:57 UTC, yalantis-ios-school commented on FortuneTeller/Global/Protocols.swift
> +    func getRandomAnswer() -> AnswersStoredData
здесь должен возвращаться тип `AnswersData`, тип слоя Application

2019-10-03 07:57 UTC, yalantis-ios-school commented on FortuneTeller/Global/Protocols.swift
> +    func isAnswerSaved(answer: String) -> Bool
в этом и следующем методах должны использоваться не строки, а модели AnswersData

2019-10-03 07:57 UTC, yalantis-ios-school commented on FortuneTeller/Presentation/ViewControllers/SettingsViewController.swift
> +        let controller = UIAlertController(title: "Sorry", message: L10n.theAnswerAlreadyExists, preferredStyle: .alert)
title использует "сырую" строку, а message - свифтгеновскую ) Надо и там и там свифтген

2019-10-06 17:01 UTC, merged